### ISSUE TITLE
Add version switcher in docs

### ISSUE THREAD

**Issue by wout** [svgdotjs/svgdotjs.github.io#27]
Create a version switcher in the header to be able to switch to the same page for a different version.

**Comment by leglock** [comment]
It looks like the version switcher exists, but it just sends you back to the documentation Home section when jumping to a different version. 

The biggest challenge with having it stay on the same page when switching appears to be different versions of the documentation use different page names for some things. For example, 2.7 has the page **Referencing** while that same page on 3.0 & 3.1 is named **Referencing / Creating Elements**. Simply renaming the version number in the URI would not be sufficient when switching pages like this.

The only solution I can think of is to create a mapping of all the pages between the different versions that is used when switching versions. Does anyone have a different approach in mind?

**Comment by Fuzzyma** [comment]
This issue is pretty old and I will close it because I added the switcher a while back.
It is not common to have a switcher which sends you to the same place in the docs of a different version because as you have guessed: The documentation changes - and that to a good extend.
Just try the bootstrap page as an example.

Adding something like a map would require tons of logic and the docs are static. So this isnt something I plan to add
